import { useEffect, useMemo, useRef, useState } from "react";
import axios from "axios";
import { FileText, UploadCloud, MessageSquare, FlaskConical, Database, Sparkles, Send, ChevronRight, Activity, Trash2, ArrowUpRight, Download } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const TEST = (role) => ({ "data-testid": role });
const initialQuestions = ["What are the main findings in this document?", "Which risks or limitations are identified?", "What actions does the author recommend?"];

function Metric({ label, value, color = "cyan" }) { return <div className="metric" data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}><span>{label}</span><strong className={color}>{value}%</strong><div className="metric-bar"><i style={{ width: `${value}%` }} /></div></div> }

export default function App() {
  const [sessionId, setSessionId] = useState(null), [documents, setDocuments] = useState([]), [chunks, setChunks] = useState([]), [messages, setMessages] = useState([]), [tab, setTab] = useState("workspace"), [question, setQuestion] = useState(""), [busy, setBusy] = useState(false), [evalBusy, setEvalBusy] = useState(false), [evalRows, setEvalRows] = useState([]), [avg, setAvg] = useState(null), [notice, setNotice] = useState("");
  const fileRef = useRef();
  useEffect(() => { axios.post(`${API}/sessions`).then(r => setSessionId(r.data.session_id)).catch(() => setNotice("Backend unavailable — refresh to reconnect.")); }, []);
  const upload = async (files) => { if (!files?.length || !sessionId) return; setBusy(true); setNotice(""); try { const form = new FormData(); [...files].forEach(f => form.append("files", f)); const r = await axios.post(`${API}/sessions/${sessionId}/documents`, form); setDocuments(d => [...d, ...r.data.documents]); const s = await axios.get(`${API}/sessions/${sessionId}`); setChunks(s.data.chunks); } catch (e) { setNotice(e.response?.data?.detail || "Could not process this file."); } finally { setBusy(false); } };
  const ask = async (e) => { e?.preventDefault(); if (!question.trim() || !sessionId || busy) return; setBusy(true); setNotice(""); try { const r = await axios.post(`${API}/ask`, { session_id: sessionId, question }); setMessages(m => [...m, r.data]); setQuestion(""); } catch (e) { setNotice(e.response?.data?.detail || "Gemini could not answer right now."); } finally { setBusy(false); } };
  const evaluate = async () => { setEvalBusy(true); setNotice(""); try { const r = await axios.post(`${API}/evaluate`, { session_id: sessionId, questions: initialQuestions }); setEvalRows(r.data.rows); setAvg(r.data.average); } catch (e) { setNotice(e.response?.data?.detail || "Evaluation could not run."); } finally { setEvalBusy(false); } };
  const latest = messages.at(-1), activeMetric = latest?.metrics || { retrieval: 0, relevance: 0, groundedness: 0 };
  const nav = [{ id: "workspace", label: "Workspace", icon: MessageSquare }, { id: "inspector", label: "Vector Inspector", icon: Database }, { id: "evaluation", label: "Evaluation Lab", icon: FlaskConical }];
  return <main className="app-shell" data-testid="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={16} /></div><div><b>lattice</b><small>document intelligence</small></div></div><div className="workspace-label">CURRENT WORKSPACE</div><div className="workspace-pill"><span className="live-dot" /> Research desk <ChevronRight size={14} /></div><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? "nav-item active" : "nav-item"} onClick={() => setTab(id)} {...TEST(`nav-${id}`)}><Icon size={17} />{label}{id === "evaluation" && <span className="nav-badge">NEW</span>}</button>)}</nav><div className="sidebar-bottom"><div className="model-card"><span className="model-status" /> <div><small>POWERED BY</small><b>Gemini 3.1 Pro</b></div><ArrowUpRight size={14} /></div><p>Session-only mode<br />Your files disappear on exit.</p></div></aside>
    <section className="content"><header className="topbar"><div><span className="eyebrow">DOCUMENT INTELLIGENCE / 01</span><h1>{tab === "workspace" ? "Ask your documents." : tab === "inspector" ? "Vector store inspector." : "Measure what matters."}</h1></div><div className="top-actions"><a className="download-link" href={`${API}/download/source-zip`} download="rag-document-intelligence-assistant.zip" {...TEST("download-source-zip-button")}><Download size={14} /> ZIP</a><span className="session-chip" data-testid="session-status"><Activity size={13} /> SESSION ACTIVE</span><button className="icon-btn" title="Clear session" onClick={() => { setDocuments([]); setChunks([]); setMessages([]); }} {...TEST("clear-session-button")}><Trash2 size={16} /></button><div className="avatar" data-testid="user-avatar">RD</div></div></header>{notice && <div className="notice" data-testid="error-notice">{notice}</div>}
      {tab === "workspace" && <div className="workspace-grid"><section className="chat-panel"><div className="panel-head"><div><span className="eyebrow">LIVE ASSISTANT</span><h2>Grounded answers, not guesses.</h2></div><span className="model-tag"><span className="live-dot" /> Gemini</span></div>{!documents.length && !messages.length ? <div className="empty-chat" data-testid="empty-workspace"><div className="empty-icon"><FileText size={23} /></div><h3>Start with a source</h3><p>Drop in a report, research note, or dataset. I’ll map its key ideas and make them queryable.</p><button className="primary-btn" onClick={() => fileRef.current?.click()} {...TEST("empty-upload-button")}><UploadCloud size={16} /> Upload documents</button></div> : <div className="message-list">{messages.map((m, i) => <article className="message" key={m.id} data-testid={`answer-message-${i}`}><div className="question"><span className="question-mark">Q</span><span>{m.question}</span></div><div className="answer"><div className="ai-mark"><Sparkles size={14} /></div><div><p>{m.answer}</p><div className="source-row">{m.sources.map((s, j) => <span key={j} className="source-chip" data-testid={`source-chip-${i}-${j}`}><FileText size={11} /> {s.source} · {s.score}</span>)}</div></div></div></article>)}</div>}<form className="ask-form" onSubmit={ask}><input value={question} onChange={e => setQuestion(e.target.value)} placeholder={documents.length ? "Ask anything across your sources…" : "Upload a document to begin…"} disabled={!documents.length || busy} {...TEST("question-input")} /><button type="submit" disabled={!documents.length || busy || !question.trim()} {...TEST("ask-submit-button")}><Send size={16} /></button></form></section>
        <aside className="right-rail"><div className="rail-section"><div className="rail-title"><span>YOUR SOURCES</span><button onClick={() => fileRef.current?.click()} {...TEST("add-document-button")}><UploadCloud size={15} /> Add</button></div><input ref={fileRef} type="file" multiple accept=".pdf,.txt,.docx,.csv" onChange={e => upload(e.target.files)} hidden {...TEST("document-file-input")} />{documents.length ? documents.map(d => <div className="doc-row" key={d.id} data-testid={`document-${d.id}`}><div className="file-icon"><FileText size={15} /></div><div><b>{d.name}</b><small>{d.type} · {d.chunks} chunks · {d.words.toLocaleString()} words</small></div><span className="check">✓</span></div>) : <div className="rail-empty">No documents yet<br /><span>PDF · TXT · DOCX · CSV</span></div>}</div><div className="rail-section metrics-section"><div className="rail-title"><span>ANSWER QUALITY</span><span className="tiny-label">LATEST</span></div><Metric label="Retrieval" value={activeMetric.retrieval} /><Metric label="Relevance" value={activeMetric.relevance} color="indigo" /><Metric label="Groundedness" value={activeMetric.groundedness} color="green" /><p className="metric-note"><span /> Scores appear after your first answer</p></div></aside></div>}
      {tab === "inspector" && <div className="inspector-page"><div className="page-intro"><div><span className="eyebrow">SEMANTIC INDEX / IN-MEMORY</span><h2>Every chunk, visible.</h2><p>Inspect the text units created for semantic retrieval in this session.</p></div><div className="stat-block"><b>{chunks.length}</b><span>indexed chunks</span></div></div><div className="table-wrap"><div className="table-head"><span>CHUNK</span><span>SOURCE</span><span>POSITION</span><span>STATUS</span></div>{chunks.length ? chunks.map((c, i) => <div className="table-row" key={c.id} data-testid={`chunk-row-${i}`}><code>{c.id.slice(0, 12)}…</code><b>{c.doc_name}</b><span>Chunk {c.index}</span><em><i /> indexed</em></div>) : <div className="table-empty">Upload documents in Workspace to populate the index.</div>}</div></div>}
      {tab === "evaluation" && <div className="evaluation-page"><div className="page-intro"><div><span className="eyebrow">EVALUATION HARNESS / BENCHMARK</span><h2>Does the answer hold up?</h2><p>Run a small question set against your current retrieval pipeline and compare the signal.</p></div><button className="primary-btn" onClick={evaluate} disabled={evalBusy || !documents.length} {...TEST("run-evaluation-button")}><FlaskConical size={16} /> {evalBusy ? "Running…" : "Run evaluation"}</button></div><div className="eval-overview"><div><small>BENCHMARK QUESTIONS</small><b>{initialQuestions.length}</b><span>curated prompts</span></div><div><small>RETRIEVAL QUALITY</small><b className="cyan">{avg?.retrieval || "—"}%</b><span>context match</span></div><div><small>FAITHFULNESS</small><b className="green">{avg?.groundedness || "—"}%</b><span>grounded answers</span></div></div><div className="eval-list">{(evalRows.length ? evalRows : initialQuestions.map(q => ({ question: q }))).map((r, i) => <div className="eval-row" key={i} data-testid={`evaluation-row-${i}`}><span className="eval-num">0{i + 1}</span><div><b>{r.question}</b>{r.answer && <p>{r.answer}</p>}</div>{r.retrieval ? <div className="mini-scores"><span>RET <b>{r.retrieval}</b></span><span>REL <b>{r.relevance}</b></span><span>GND <b>{r.groundedness}</b></span></div> : <span className="pending">READY TO RUN</span>}</div>)}</div></div>}
    </section><div className="ambient-line" /></main>;
}